name: hw1_env
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=1.8.0
  - torchvision=0.9.0
  - pillow # version 7 breaks torchvision 0.4.2 and earlier
  - ipython
  - numpy
  - scikit-learn=1.0.2
  - cudatoolkit
  - jupyterlab
  - matplotlib
  - jupyter
  - pandas
  - cython
  - pytest
  - tqdm
  - opencv
  - ffmpeg
  - freetype
  - swig # for box2d on Windows
  - pip
  - pip:
    - nbmerge
    - pytest-xdist
    - gym
    - atari-py
    - box2d-py

